import random 

for i in range(999):
    dun_goal = random.choice(["Stop the dungeon's monstrous inhabitants from raiding the surface world.","Foil a villain's evil scheme.", "Destroy a magical threat inside the dungeon.","Acquire treasure","Find a particular item for a specific purpose.","Retrieve a stolen item hidden in the dungeon.","Find information needed for a special purpose.","Rescue a captive.","Discover the fate of a previous adventuring party.","Find an NPC who disappeared in the area.","Slay a dragon or some other challenging monster.","Discover the nature and origin of a strange location or phenomenon.","Pursue fleeing foes taking refuge in the dungeon.","Escape from captivity in the dungeon.","Escape from captivity in the dungeon.","Clear a ruin so it can be rebuilt and reoccupied.","Discover why a villain is interested in the dungeon.","Win a bet or complete a rite of passage by surviving in the dungeon for a certain amount oftime.","Parley with a villain in the dungeon.","Hide from a threat outside the dungeon.","rolltwice"])
    dun_goal_list = ["Stop the dungeon's monstrous inhabitants from raiding the surface world.","Foil a villain's evil scheme.", "Destroy a magical threat inside the dungeon.","Acquire treasure","Find a particular item for a specific purpose.","Retrieve a stolen item hidden in the dungeon.","Find information needed for a special purpose.","Rescue a captive.","Discover the fate of a previous adventuring party.","Find an NPC who disappeared in the area.","Slay a dragon or some other challenging monster.","Discover the nature and origin of a strange location or phenomenon.","Pursue fleeing foes taking refuge in the dungeon.","Escape from captivity in the dungeon.","Escape from captivity in the dungeon.","Clear a ruin so it can be rebuilt and reoccupied.","Discover why a villain is interested in the dungeon.","Win a bet or complete a rite of passage by surviving in the dungeon for a certain amount oftime.","Parley with a villain in the dungeon.","Hide from a threat outside the dungeon."]
    wil_goal = random.choice([f"Locate a dungeon or other site of interest. Why? To {dun_goal}","Assess the scope of a natural or unnatural disaster.","Escort an NPC to a destination.","Arrive at a destination without being seen by the villain's forces.","Stop monsters from raiding caravans and farms.","Establish trade with a distant town.","Protect a caravan traveling to a distant town.","Map a new land.","Find a place to establish a colony.","Find a natural resource.","Hunt a specific monster.","Return home from a distant place.","Obtain information from a reclusive hermit.","Find an object that was lost in the wilds.","Discover the fate of a missing group of explorers.","Pursue fleeing foes.","Assess the size of an approaching army.","Escape the reign of a tyrant.","Protect a wilderness site from attackers.","rolltwice"])
    wil_goal_list = [f"Locate a dungeon or other site of interest. Why? To {dun_goal}","Assess the scope of a natural or unnatural disaster.","Escort an NPC to a destination.","Arrive at a destination without being seen by the villain's forces.","Stop monsters from raiding caravans and farms.","Establish trade with a distant town.","Protect a caravan traveling to a distant town.","Map a new land.","Find a place to establish a colony.","Find a natural resource.","Hunt a specific monster.","Return home from a distant place.","Obtain information from a reclusive hermit.","Find an object that was lost in the wilds.","Discover the fate of a missing group of explorers.","Pursue fleeing foes.","Assess the size of an approaching army.","Escape the reign of a tyrant.","Protect a wilderness site from attackers."] 
    ot_goal = random.choice(["Seize control of a fortified location such as a fortress, town, or ship.","Defend a location from attackers.","Retrieve an object from inside a secure location in a settlement.","Retrieve an object from a caravan.","Salvage an object or goods from a lost vessel or caravan.","Break a prisoner out of a jail or prison camp.","Escape from a jail or prison camp.","Successfully travel through an obstacle course to gain recognition or reward.","Infiltrate a fortified location","Find the source of strange occurrences in a haunted house or other location.","Interfere with the operation of a business.","Rescue a character, monster, or object from a natural or unnatural disaster."])
    adv_villain = random.choice(["Beast or monstrosity with no particular agenda","Aberration bent on corruption or domination.","Fiend bent on corruption or destruction.","Dragon bent on domination and plunder","Giant bent on plunder.","Undead with any agenda.","Fey with a mysterious goal.","Humanoid cultist.","Humanoid conqueror.","Humanoid seeking revenge.","Humanoid schemer seeking to rule.","Humanoid criminal mastermind.","Humanoid rader or ravager.","Humanoid under a curse.","Misguided humanoid zealot."])
    adv_allies = random.choice(["Skilled adventurer.","Inexperienced adventurer.","Enthusiastic commoner.","Soldier.","Priest.","Sage.","Revenge seeker.","Raving lunatic.","Celestial ally.","Fey ally.","Disguised monster.","Villain posing as an ally."])
    adv_intro = random.choice(["While traveling in the wilderness, the characters fall into a sinkhole that opens beneath their feet, dropping them into the adventure location.","While traveling in the wilderness, the characters notice the entrance to the adventure location.","While traveling on a road, the characters are attacked by monsters that flee into the nearby adventure location.","The adventurers find a map on a dead body. In add ition to the map setting up the adventure, the adventure's villain wants the map.","A mysterious magic item or a cruel villain teleports the characters to the adventure location.","A stranger approaches the characters in a tavern and urges them toward the adventure location.","A town or village needs volunteers to go to the adventure location.","An NPC the characters care about needs them to go to the adventure location.","An NPC the characters must obey orders them to go to the adventure location.","An NPC the characters respect asks them to go to the adventure location.","One night, the characters all dream about entering the adventure location.","A ghost appears and terrorizes a village. Research reveals that it can be put to rest only by entering the adventure location."])
    adv_climax = ["An ally betrays the adventurers as they're about to achieve their goal. (Use this climax carefully, and don't overuse it.)","","The adventurers confront the main villain and a group of minions in a bloody battle to the finish.","The adventurers chase the villain while dodging obstacles designed to thwart them, leading to a final confrontation in or outside the villain's refuge.","The actions of the adventurers or the vilain result in a cataclysmic event that the adventurers must escape.","The adventurers race to the site where the villain is bringing a master plan to its conclusion, arriving just as that plan is about to be completed.","The villain and two or three lieutenants perform separate rites in a large room. The adventurers must disrupt all the rites at the same time.","A portal opens to another plane of existence. Creatures on the other side spill out, forcing the adventurers to close the portal and deal with the villain at the same time.","Traps, hazards, or animated objects turn against the adventurers while the main villain attacks.","The dungeon begins to collapse while the adventurers face the main villain, who attempts to escape in the chaos.","A threat more powerful than the adventurers appears, destroys the main villain, and then turns its attention on the characters.","The adventurers must choose whether to pursue the fleeing main villain or save an NPC they care about or a group of innocents.","The adventurers must discover the main villain's secret weakness before they can hope to defeat that villain."]

    #unused: adv_intro_list = ["While traveling in the wilderness, the characters fall into a sinkhole that opens beneath their feet, dropping them into the adventure location.","While traveling in the wilderness, the characters notice the entrance to the adventure location.","While traveling on a road, the characters are attacked by monsters that flee into the nearby adventure location.","The adventurers find a map on a dead body. In add ition to the map setting up the adventure, the adventure's villain wants the map.","A mysterious magic item or a cruel villain teleports the characters to the adventure location.","A stranger approaches the characters in a tavern and urges them toward the adventure location.","A town or village needs volunteers to go to the adventure location.","An NPC the characters care about needs them to go to the adventure location.","An NPC the characters must obey orders them to go to the adventure location.","An NPC the characters respect asks them to go to the adventure location.","One night, the characters all dream about entering the adventure location.","A ghost appears and terrorizes a village. Research reveals that it can be put to rest only by entering the adventure location."]

    input("press enter for an adventure.")
    print("-------------------------------")
    print("Adventure start: " + adv_intro)
    print("Main villain: " + adv_villain)
    print("Ally: " + adv_allies)

    if wil_goal == "rolltwice":
        print("Wilderness goals:")
        print(random.choices(wil_goal_list, k = 2))
    else:
        print("Wilderness goal: " + wil_goal)

    if dun_goal == "rolltwice":
        print("Dungeon goals:")
        print(random.choices(dun_goal_list, k = 2))
    else:
        print("Dungeon goal: " + dun_goal)
    print("Other goals: " + ot_goal)
    climax = random.choices(adv_climax, weights= [1, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10], k=1 )
    print("Adventure climax: " + str(climax))
        
    print(" ")

